### ISSUE TITLE
[BUG] AttributeError: module 'collections' has no attribute 'Mapping'

### ISSUE THREAD

**Issue by ProgrammingLife** [danielgatis/rembg#364]
**Describe the bug**
Just installed the software but I can't even start it. Can you please give some advice what to check to run it?

**To Reproduce**
```
$ python3.10 -m PyInstaller rembg.py
....

$ python3.10 -m pip install rembg[gpu]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: rembg[gpu] in /home/prlife/.local/lib/python3.10/site-packages (2.0.29)
Requirement already satisfied: opencv-python-headless==4.6.0.66 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (4.6.0.66)
Requirement already satisfied: pymatting==1.1.8 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (1.1.8)
Requirement already satisfied: aiohttp==3.8.1 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (3.8.1)
Requirement already satisfied: pillow==9.3.0 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (9.3.0)
Requirement already satisfied: tqdm==4.64.1 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (4.64.1)
Requirement already satisfied: uvicorn==0.20.0 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (0.20.0)
Requirement already satisfied: pooch==1.6.0 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (1.6.0)
Requirement already satisfied: onnxruntime==1.13.1 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (1.13.1)
Requirement already satisfied: filetype==1.2.0 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (1.2.0)
Requirement already satisfied: scipy==1.9.3 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (1.9.3)
Requirement already satisfied: python-multipart==0.0.5 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (0.0.5)
Requirement already satisfied: click==8.1.3 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (8.1.3)
Requirement already satisfied: fastapi==0.87.0 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (0.87.0)
Requirement already satisfied: scikit-image==0.19.3 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (0.19.3)
Requirement already satisfied: watchdog==2.1.9 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (2.1.9)
Requirement already satisfied: asyncer==0.0.2 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (0.0.2)
Requirement already satisfied: numpy==1.23.5 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (1.23.5)
Requirement already satisfied: imagehash==4.3.1 in /home/prlife/.local/lib/python3.10/site-packages (from rembg[gpu]) (4.3.1)
Collecting onnxruntime-gpu==1.12.1
  Downloading onnxruntime_gpu-1.12.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (111.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 MB 5.7 MB/s eta 0:00:00
Requirement already satisfied: yarl<2.0,>=1.0 in /home/prlife/.local/lib/python3.10/site-packages (from aiohttp==3.8.1->rembg[gpu]) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in /home/prlife/.local/lib/python3.10/site-packages (from aiohttp==3.8.1->rembg[gpu]) (1.3.3)
Requirement already satisfied: attrs>=17.3.0 in /home/prlife/.local/lib/python3.10/site-packages (from aiohttp==3.8.1->rembg[gpu]) (22.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/prlife/.local/lib/python3.10/site-packages (from aiohttp==3.8.1->rembg[gpu]) (6.0.3)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/prlife/.local/lib/python3.10/site-packages (from aiohttp==3.8.1->rembg[gpu]) (2.1.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/prlife/.local/lib/python3.10/site-packages (from aiohttp==3.8.1->rembg[gpu]) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /home/prlife/.local/lib/python3.10/site-packages (from aiohttp==3.8.1->rembg[gpu]) (1.3.1)
Requirement already satisfied: anyio<4.0.0,>=3.4.0 in /home/prlife/.local/lib/python3.10/site-packages (from asyncer==0.0.2->rembg[gpu]) (3.6.2)
Requirement already satisfied: starlette==0.21.0 in /home/prlife/.local/lib/python3.10/site-packages (from fastapi==0.87.0->rembg[gpu]) (0.21.0)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in /home/prlife/.local/lib/python3.10/site-packages (from fastapi==0.87.0->rembg[gpu]) (1.10.2)
Requirement already satisfied: PyWavelets in /home/prlife/.local/lib/python3.10/site-packages (from imagehash==4.3.1->rembg[gpu]) (1.4.1)
Requirement already satisfied: flatbuffers in /home/prlife/.local/lib/python3.10/site-packages (from onnxruntime==1.13.1->rembg[gpu]) (22.12.6)
Requirement already satisfied: coloredlogs in /home/prlife/.local/lib/python3.10/site-packages (from onnxruntime==1.13.1->rembg[gpu]) (15.0.1)
Requirement already satisfied: sympy in /home/prlife/.local/lib/python3.10/site-packages (from onnxruntime==1.13.1->rembg[gpu]) (1.11.1)
Requirement already satisfied: packaging in /home/prlife/.local/lib/python3.10/site-packages (from onnxruntime==1.13.1->rembg[gpu]) (22.0)
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (from onnxruntime==1.13.1->rembg[gpu]) (3.0.0)
Requirement already satisfied: appdirs>=1.3.0 in /home/prlife/.local/lib/python3.10/site-packages (from pooch==1.6.0->rembg[gpu]) (1.4.4)
Requirement already satisfied: requests>=2.19.0 in /home/prlife/.local/lib/python3.10/site-packages (from pooch==1.6.0->rembg[gpu]) (2.28.1)
Requirement already satisfied: numba!=0.49.0 in /usr/lib/python3/dist-packages (from pymatting==1.1.8->rembg[gpu]) (0.34.0)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from python-multipart==0.0.5->rembg[gpu]) (1.11.0)
Requirement already satisfied: networkx>=2.2 in /home/prlife/.local/lib/python3.10/site-packages (from scikit-image==0.19.3->rembg[gpu]) (2.8.8)
Requirement already satisfied: tifffile>=2019.7.26 in /home/prlife/.local/lib/python3.10/site-packages (from scikit-image==0.19.3->rembg[gpu]) (2022.10.10)
Requirement already satisfied: imageio>=2.4.1 in /home/prlife/.local/lib/python3.10/site-packages (from scikit-image==0.19.3->rembg[gpu]) (2.22.4)
Requirement already satisfied: h11>=0.8 in /home/prlife/.local/lib/python3.10/site-packages (from uvicorn==0.20.0->rembg[gpu]) (0.14.0)
Requirement already satisfied: sniffio>=1.1 in /home/prlife/.local/lib/python3.10/site-packages (from anyio<4.0.0,>=3.4.0->asyncer==0.0.2->rembg[gpu]) (1.3.0)
Requirement already satisfied: idna>=2.8 in /home/prlife/.local/lib/python3.10/site-packages (from anyio<4.0.0,>=3.4.0->asyncer==0.0.2->rembg[gpu]) (3.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/prlife/.local/lib/python3.10/site-packages (from pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2->fastapi==0.87.0->rembg[gpu]) (4.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pooch==1.6.0->rembg[gpu]) (2018.1.18)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pooch==1.6.0->rembg[gpu]) (1.22)
Requirement already satisfied: humanfriendly>=9.1 in /home/prlife/.local/lib/python3.10/site-packages (from coloredlogs->onnxruntime==1.13.1->rembg[gpu]) (10.0)
Requirement already satisfied: mpmath>=0.19 in /home/prlife/.local/lib/python3.10/site-packages (from sympy->onnxruntime==1.13.1->rembg[gpu]) (1.2.1)
Installing collected packages: onnxruntime-gpu
Successfully installed onnxruntime-gpu-1.12.1


$ python3.10 -m pip install requests --upgrade                                
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /home/prlife/.local/lib/python3.10/site-packages (2.28.1)
Requirement already satisfied: idna<4,>=2.5 in /home/prlife/.local/lib/python3.10/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests) (1.22)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/prlife/.local/lib/python3.10/site-packages (from requests) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2018.1.18)

$ head -1 $( which rembg )
#!/usr/bin/python3.10

$ rembg --help
Traceback (most recent call last):
  File "/home/prlife/.local/bin/rembg", line 5, in <module>
    from rembg.cli import main
  File "/home/prlife/apps/rembg/rembg-2.0.29/rembg/__init__.py", line 5, in <module>
    from .bg import remove
  File "/home/prlife/apps/rembg/rembg-2.0.29/rembg/bg.py", line 16, in <module>
    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
  File "/home/prlife/.local/lib/python3.10/site-packages/pymatting/__init__.py", line 2, in <module>
    from pymatting.util import *
  File "/home/prlife/.local/lib/python3.10/site-packages/pymatting/util/__init__.py", line 2, in <module>
    from pymatting.util.kdtree import KDTree, knn
  File "/home/prlife/.local/lib/python3.10/site-packages/pymatting/util/kdtree.py", line 2, in <module>
    from numba import njit, prange
  File "/usr/lib/python3/dist-packages/numba/__init__.py", line 9, in <module>
    from . import config, errors, runtests, types
  File "/usr/lib/python3/dist-packages/numba/types/__init__.py", line 7, in <module>
    from .abstract import *
  File "/usr/lib/python3/dist-packages/numba/types/abstract.py", line 10, in <module>
    from ..utils import cached_property
  File "/usr/lib/python3/dist-packages/numba/utils.py", line 236, in <module>
    class SortedMap(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

**Expected behavior**
Working app

**Images**
n/a

**OS Version:**
Linux Mint 18
Python 3.10

**Rembg version:**
v2.0.29

**Additional context**
n/a

**Comment by jangop** [comment]
> but it actually doesn't work with python3.10?

It does work with 3.10: https://github.com/danielgatis/rembg/actions/runs/3695953301/jobs/6258997732

The problem appears related to dependencies beyond the version of Python.
